const gods = {
  athena: {
    index:'05', name:'Athena', symbol:'Α', specialty:'Sabedoria & estratégia', domain:'DEUSA DA SABEDORIA', caption:'ATHENA · MÁRMORE E MEMÓRIA', title:'A sabedoria<br>tem <em>armadura.</em>', description:'Entre a estratégia e a coragem, Athena ensina que a força mais duradoura nasce de uma mente desperta.', quoteSource:'A CORUJA DE ATENAS', quote:'“A inteligência vê o caminho antes que os pés o encontrem.”', kicker:'CADERNO DE ATHENA', image:'assets/athena.png',
    stories:[['01 · ESTRATÉGIA','A cidade que nasceu de uma oliveira','A disputa entre Athena e Poseidon transformou um gesto de cuidado no símbolo de uma cidade.','5 MIN DE LEITURA','Α','Quando os deuses disputaram a proteção da Ática, Poseidon golpeou a rocha e fez jorrar água salgada. Athena ofereceu algo menos estrondoso: uma oliveira, fonte de alimento, óleo e madeira. Os habitantes escolheram a dádiva que podia acompanhá-los por gerações — e a cidade passou a carregar o nome da deusa.'],['02 · METAMORFOSE','Aracne e o preço do orgulho','Uma tecelã desafia a deusa — e o fio entre talento e arrogância se torna lenda.','7 MIN DE LEITURA','ϟ','Aracne tecia com tal precisão que todos vinham admirar seu trabalho. Convencida de que seu talento não devia nada aos deuses, desafiou Athena para um concurso. As duas tapeçarias eram extraordinárias; a de Aracne retratava, sem reverência, os enganos divinos. Ferida pelo desafio, Athena rompeu o tecido. A jovem escolheu a corda; a deusa, num gesto de piedade tardia, transformou-a em aranha — tecelã para sempre.'],['03 · JORNADA','A armadura de Perseu','Com um escudo polido como espelho, Athena guia o herói por uma missão impossível.','6 MIN DE LEITURA','◇','Para enfrentar Medusa sem encontrar seu olhar petrificante, Perseu recebeu de Athena um escudo polido. O herói avançou guiado pelo reflexo, e não pela visão direta. Depois da missão, a cabeça da Górgona encontrou lugar no escudo da própria deusa: uma defesa feita daquilo que antes causava medo.']]
  },
  poseidon: {
    index:'03', name:'Poseidon', symbol:'Ψ', specialty:'Mares & terremotos', domain:'DEUS DOS MARES', caption:'POSEIDON · PEDRA E MARÉ', title:'O mar não<br>conhece <em>limites.</em>', description:'Senhor de correntes e terremotos, Poseidon lembra que toda calmaria carrega a memória de uma tempestade.', quoteSource:'AS CORRENTES DO EGEU', quote:'“O que se move nas profundezas também move o mundo.”', kicker:'CADERNO DE POSEIDON', image:'assets/poseidon.png',
    stories:[['01 · TRAVESSIA','Odisseu e o mar sem fim','Dez anos de ondas, desvios e provações no caminho de volta a Ítaca.','8 MIN DE LEITURA','Ψ','Ao ferir o ciclope Polifemo, filho de Poseidon, Odisseu atraiu a cólera do deus dos mares. Ventos contrários e monstros marinhos alongaram uma viagem que deveria ser breve. Em cada ilha, o herói precisou escolher entre a pressa e a prudência — enquanto o mar lembrava que caminho de volta também é uma prova.'],['02 · ORIGEM','A disputa pela cidade','O tridente abriu uma fonte de água salgada; uma oliveira ofereceu outro destino.','5 MIN DE LEITURA','ϟ','Poseidon golpeou a Acrópole com seu tridente e fez surgir uma fonte salgada, sinal de poder naval. Athena ofereceu a oliveira, promessa de alimento, madeira e azeite. Os habitantes escolheram a dádiva útil ao cotidiano, e o deus guardou sua mágoa nas ondas que cercam a cidade.'],['03 · CRIATURAS','As paredes de Troia','Uma promessa quebrada desperta a ira de Poseidon e muda o destino de uma guerra.','6 MIN DE LEITURA','∿','Antes da guerra, Poseidon ajudou a erguer as muralhas de Troia, pedra sobre pedra, junto de Apollo. O rei Laomedonte recusou o pagamento prometido. A ofensa atravessou os anos: quando os gregos cercaram a cidade, Poseidon tomou partido e fez do mar uma força ativa no conflito.']]
  },
  apollo: {
    index:'06', name:'Apollo', symbol:'☼', specialty:'Luz & artes', domain:'DEUS DA LUZ E DAS ARTES', caption:'APOLLO · OURO E HARMONIA', title:'A luz também<br>faz <em>perguntas.</em>', description:'Música, profecia e cura encontram seu centro em Apollo — e nem toda resposta chega sem custo.', quoteSource:'O ORÁCULO DE DELFOS', quote:'“Conhece-te a ti mesmo; escuta o que ainda não sabes.”', kicker:'CADERNO DE APOLLO', image:'assets/apollo.png',
    stories:[['01 · PROFECIA','A voz de Delfos','No umbigo do mundo, a Pítia transforma vapor e silêncio em palavras para reis.','6 MIN DE LEITURA','☼','Em Delfos, sobre as encostas do Parnaso, a sacerdotisa de Apollo recebia os visitantes que buscavam orientação. Reis e viajantes traziam perguntas; a Pítia respondia em palavras enigmáticas, interpretadas pelos sacerdotes do templo. O oráculo não removia a incerteza: dava-lhe uma forma que cada pessoa precisava decifrar.'],['02 · MÚSICA','O desafio de Marsias','Uma flauta, uma lira e a perigosa fronteira entre talento e insolência.','5 MIN DE LEITURA','♫','Marsias encontrou a flauta rejeitada por Athena e tornou-se um músico admirado. Convencido de que podia superar Apollo, desafiou o deus para uma disputa. As melodias da flauta encantaram o público, mas Apollo inverteu sua lira e tocou — algo impossível para o instrumento de Marsias. A competição terminou quando a confiança humana encontrou um limite divino.'],['03 · METAMORFOSE','Dafne, folhas de louro','Uma corrida termina em transformação — e cria um dos símbolos eternos de Apollo.','7 MIN DE LEITURA','❧','Fugindo de Apollo, Dafne pediu ajuda ao pai, o deus-rio Peneu. Seus pés criaram raízes e seus braços se cobriram de folhas: tornara-se um loureiro. Apollo acolheu as folhas como seu emblema. Desde então, a coroa de louros celebra poetas, atletas e aqueles cujo nome atravessa o tempo.']]
  },
  hades: {
    index:'13', name:'Hades', symbol:'♜', specialty:'Submundo & riquezas', domain:'SENHOR DO SUBMUNDO', caption:'HADES · SOMBRA E ROMÃ', title:'Até a sombra<br>guarda <em>sementes.</em>', description:'Guardião do mundo invisível, Hades reina sobre os ciclos que toda vida atravessa: perda, silêncio e retorno.', quoteSource:'OS PORTÕES DE ÉREBO', quote:'“Nem todo fim é ausência. Alguns guardam a forma de um começo.”', kicker:'CADERNO DE HADES', image:'assets/hades.png',
    stories:[['01 · ESTAÇÕES','O pacto de Perséfone','Uma romã, seis sementes e o acordo que desenha o ritmo das estações.','7 MIN DE LEITURA','♜','Hades acolheu Perséfone no reino dos mortos, e Deméter, sua mãe, deixou a terra estéril enquanto a procurava. Zeus intermediou um acordo. Como Perséfone havia provado sementes de romã no submundo, passaria parte do ano ao lado de Hades e parte com a mãe. Sua ida e seu retorno deram aos gregos uma imagem para as estações: a terra floresce quando a filha volta.'],['02 · JORNADA','Orfeu diante do silêncio','Um músico desce ao reino dos mortos com uma canção e uma condição.','6 MIN DE LEITURA','♫','Quando Eurídice morreu, Orfeu desceu ao submundo levando apenas sua lira. Sua música comoveu os guardiões e alcançou Hades, que aceitou devolver a jovem sob uma condição: Orfeu deveria caminhar à frente sem olhar para trás até alcançar a luz. Perto da saída, a dúvida venceu. O olhar virou despedida, e a canção passou a ser lembrada como a melodia de uma perda.'],['03 · GUARDIÃO','Cérbero e a última porta','Três cabeças guardam o limite entre os vivos e aquilo que os espera.','5 MIN DE LEITURA','◇','Cérbero vigiava a entrada do reino de Hades: recebia os que chegavam e impedia que os mortos escapassem. O cão de três cabeças tornou-se o guardião mais conhecido das fronteiras do além. Héracles precisou dominá-lo para cumprir seu último trabalho — e provar que até as portas mais temidas podem ser atravessadas.']]
  },
  zeus: {
    index:'01', name:'Zeus', symbol:'Ζ', specialty:'Céu & soberania', domain:'DEUS DO CÉU E DOS RAIOS', caption:'ZEUS · CÉU E TROVÃO', title:'O céu tem<br>voz de <em>trovão.</em>', description:'Senhor do Olimpo e guardião dos juramentos, Zeus governa entre o poder e suas próprias contradições.', quoteSource:'OS CÉUS DO OLIMPO', quote:'“Até o maior dos poderes responde às leis que promete guardar.”', kicker:'CADERNO DE ZEUS', image:'assets/zeus.png',
    stories:[['01 · ORIGEM','O filho que escapou de Cronos','Uma profecia, uma pedra envolta em panos e o nascimento de uma nova ordem.','6 MIN','Ζ','Reia salvou Zeus ao escondê-lo numa gruta de Creta e entregar a Cronos uma pedra enrolada em panos. Quando cresceu, Zeus libertou os irmãos e enfrentou o titã: uma nova geração rompeu o ciclo da anterior.'],['02 · DESTINO','O raio dos Ciclopes','Uma aliança forjada no Tártaro entrega a Zeus sua arma mais conhecida.','5 MIN','ϟ','Durante a Titanomaquia, Zeus libertou os Ciclopes, que lhe deram o raio. Com a ajuda deles e dos Hecatônquiros, os olímpicos venceram os Titãs e abriram caminho para uma nova ordem.'],['03 · JURAMENTO','A balança dos destinos','Mesmo o soberano consulta forças que não controla inteiramente.','5 MIN','⚖','Em diferentes poemas, Zeus pesa destinos e ouve as Moiras, fiandeiras do curso da vida. O rei dos deuses exerce enorme poder, mas a ordem do universo não se resume à sua vontade.']]
  },
  hera: {
    index:'02', name:'Hera', symbol:'Η', specialty:'União & realeza', domain:'DEUSA DO CASAMENTO E DA REALEZA', caption:'HERA · PÚRPURA E PLUMA', title:'A rainha<br>também <em>escolhe.</em>', description:'Hera representa soberania, família e alianças — uma presença poderosa num mundo que raramente lhe oferece paz.', quoteSource:'O TRONO DE ARGOS', quote:'“A dignidade não depende da harmonia ao redor.”', kicker:'CADERNO DE HERA', image:'assets/hera.png',
    stories:[['01 · TRANSFORMAÇÃO','Io e os olhos de Argos','Uma princesa transformada em novilha atravessa terras sob guarda incessante.','6 MIN','Η','Hera colocou Argos Panoptes, o gigante de muitos olhos, como guardião de Io. Hermes o venceu; depois, os olhos de Argos passaram a adornar a cauda do pavão, ave associada a Hera.'],['02 · LUGAR','A deusa de muitas cidades','De Argos a Samos, santuários contam diferentes faces da rainha do Olimpo.','5 MIN','♧','Hera tinha grandes centros de culto em Argos e Samos. Nos templos, aparecia como rainha, protetora do casamento e força cívica — com tradições próprias em cada comunidade.'],['03 · SÍMBOLO','O pavão e a memória de Argos','Uma constelação de olhos transforma uma história em emblema.','4 MIN','✧','Hera teria colocado os olhos de Argos nas penas do pavão. A ave combina beleza e vigilância e tornou-se um de seus símbolos mais reconhecidos.']]
  },
  demeter: {
    index:'04', name:'Deméter', symbol:'Δ', specialty:'Colheita & ciclos', domain:'DEUSA DA COLHEITA E DA TERRA', caption:'DEMÉTER · TERRA E ESTAÇÃO', title:'A terra<br>lembra o <em>retorno.</em>', description:'Deusa dos grãos e da fertilidade, Deméter dá forma aos ciclos de perda, espera e renovação que sustentam a vida.', quoteSource:'OS CAMPOS DE ELÊUSIS', quote:'“Toda semente conhece o escuro antes de encontrar a luz.”', kicker:'CADERNO DE DEMÉTER', image:'assets/demeter.png',
    stories:[['01 · MISTÉRIO','Os ritos de Elêusis','Um culto antigo promete esperança por meio do ciclo de Perséfone.','6 MIN','Δ','Em Elêusis, iniciados participavam de ritos secretos dedicados a Deméter e Perséfone. O mito da filha que parte ao submundo e retorna oferecia uma imagem de renovação.'],['02 · ENSINO','Triptolemo e o primeiro grão','Deméter entrega à humanidade o conhecimento de cultivar a terra.','5 MIN','♧','Acolhida na casa de Céleo, Deméter ensinou a Triptolemo a agricultura. Em seu carro alado, ele levou sementes e conhecimento a outras regiões.'],['03 · ESTAÇÃO','O campo à espera da filha','A tristeza de uma mãe interrompe a colheita e desenha o inverno.','5 MIN','❧','Quando Perséfone desapareceu, Deméter abandonou os campos. O acordo que permitiu o retorno periódico da jovem restaurou também o ritmo da agricultura.']]
  },
  artemis: {
    index:'07', name:'Ártemis', symbol:'☾', specialty:'Caça & natureza', domain:'DEUSA DA CAÇA E DA NATUREZA', caption:'ÁRTEMIS · PRATA E FLORESTA', title:'A noite<br>também é <em>território.</em>', description:'Arqueira e guardiã dos espaços selvagens, Artemis existe além das fronteiras traçadas pelos homens.', quoteSource:'AS MATAS DE ÁRCADE', quote:'“Há caminhos que só aparecem quando a cidade silencia.”', kicker:'CADERNO DE ÁRTEMIS', image:'assets/artemis.png',
    stories:[['01 · METAMORFOSE','Acteão e o olhar proibido','Um caçador vê a deusa e paga o preço de cruzar uma fronteira.','5 MIN','☾','Acteão encontrou Artemis enquanto a deusa se banhava. Transformado em cervo, foi perseguido por seus próprios cães. O mito marca a mata como domínio sagrado, com limites que não devem ser violados.'],['02 · DESTINO','Ifigênia em Áulis','Um vento parado transforma a jornada para Troia numa escolha impossível.','6 MIN','ϟ','Com a frota grega presa pela falta de vento, Artemis exigiu um sacrifício numa versão do mito; em outra, substituiu Ifigênia por uma corça. A história deixa em aberto o custo humano da guerra.'],['03 · COMPANHIA','As companheiras da caçadora','Ninfas seguem Artemis pelos bosques sob uma promessa de liberdade.','4 MIN','♧','Artemis percorria os bosques com ninfas que compartilhavam sua vida de caça e movimento. As histórias retratam uma divindade independente, ligada à proteção dos animais e dos jovens.']]
  },
  ares: {
    index:'08', name:'Ares', symbol:'Α', specialty:'Guerra & coragem', domain:'DEUS DA GUERRA', caption:'ARES · BRONZE E CINZA', title:'A guerra<br>revela o <em>custo.</em>', description:'Ares encarna o furor do combate — força temida até pelos deuses, inseparável da devastação que deixa.', quoteSource:'OS CAMPOS DE TRÓIA', quote:'“A vitória também deixa marcas em quem a alcança.”', kicker:'CADERNO DE ARES', image:'assets/ares.png',
    stories:[['01 · JULGAMENTO','Ares diante do Areópago','Uma disputa entre deuses dá nome ao tribunal de Atenas.','5 MIN','Α','Segundo uma tradição, Ares matou Halirrótio ao defender sua filha Alcipe. O caso foi julgado numa colina que passou a se chamar Areópago, “colina de Ares”.'],['02 · BATALHA','O deus no campo de Troia','Ares entra numa guerra em que nenhum dos lados é invencível.','6 MIN','ϟ','Na Ilíada, Ares combate ao lado dos troianos e enfrenta Athena, que apoia os aqueus. Ferido, precisa deixar o campo; até o deus da guerra pode ser vencido.'],['03 · SEGREDO','A rede de Hefesto','Uma armadilha expõe o caso de Ares e Afrodite diante dos olímpicos.','5 MIN','◇','Hefesto preparou uma rede invisível para capturar Ares e Afrodite. Presos, os dois foram exibidos aos deuses reunidos: desejo, engenho e aparências se cruzam no mito.']]
  },
  aphrodite: {
    index:'09', name:'Afrodite', symbol:'Α', specialty:'Amor & beleza', domain:'DEUSA DO AMOR E DA BELEZA', caption:'AFRODITE · ROSA E ESPUMA', title:'O desejo<br>move <em>mundos.</em>', description:'Nascida do mar em uma tradição, Afrodite transforma atração e beleza em forças capazes de alterar destinos.', quoteSource:'AS MARGENS DE CHIPRE', quote:'“O que nos atrai também muda a direção da viagem.”', kicker:'CADERNO DE AFRODITE', image:'assets/aphrodite.png',
    stories:[['01 · ESCOLHA','O pomo de ouro','Uma disputa entre deusas oferece a Paris uma escolha que conduzirá à guerra.','6 MIN','Α','Éris lançou um pomo de ouro destinado à mais bela. Hera, Athena e Afrodite disputaram o título; Paris escolheu Afrodite, que lhe prometeu o amor de Helena. A escolha tornou-se um dos começos da Guerra de Troia.'],['02 · ENCONTRO','Afrodite chega a Chipre','Uma deusa emerge das águas e encontra uma ilha pronta para recebê-la.','4 MIN','∿','Na Teogonia de Hesíodo, Afrodite nasce da espuma do mar e chega a Citera e depois a Chipre. Outras tradições contam sua origem de maneiras diferentes; todas ligam a deusa ao desejo e ao mar.'],['03 · MÚSICA','Adônis e a flor breve','Um amor interrompido deixa sua memória na volta de cada primavera.','5 MIN','❧','Afrodite amou Adônis, jovem caçador cuja vida terminou cedo. Em algumas versões, a disputa por seu tempo envolve Perséfone. A flor que nasce onde caiu torna-se imagem de beleza breve e retorno.']]
  },
  hephaestus: {
    index:'10', name:'Hefesto', symbol:'Η', specialty:'Forja & invenção', domain:'DEUS DA FORJA E DO FOGO', caption:'HEFESTO · FERRO E BRASA', title:'A beleza<br>também se <em>forja.</em>', description:'Artífice dos deuses, Hefesto transforma fogo e matéria em objetos que carregam engenho, história e poder.', quoteSource:'A FORJA DO ETNA', quote:'“A mão que constrói também muda o destino.”', kicker:'CADERNO DE HEFESTO', image:'assets/hephaestus.png',
    stories:[['01 · ENGENHO','O trono que prendeu Hera','Uma obra dourada revela uma antiga ferida dentro da família divina.','5 MIN','Η','Hefesto enviou a Hera um trono magnífico, mas encantado. Quando a rainha se sentou, não conseguiu levantar. Os deuses precisaram negociar com o artífice para libertá-la.'],['02 · ARMADURA','O escudo de Aquiles','Hefesto grava um mundo inteiro na superfície de uma arma.','6 MIN','◇','A pedido de Tétis, Hefesto forjou novas armas para Aquiles. No escudo, gravou cidades, campos, danças, constelações e o oceano: uma imagem da vida que a guerra ameaça.'],['03 · OFÍCIO','As servas de ouro','Autômatos feitos pelo deus caminham e trabalham ao lado do mestre.','4 MIN','ϟ','Na Ilíada, Hefesto conta com servas de ouro dotadas de voz e movimento. Suas criações antecipam, no imaginário antigo, máquinas capazes de agir por conta própria.']]
  },
  hermes: {
    index:'11', name:'Hermes', symbol:'Ϻ', specialty:'Viagens & mensagens', domain:'DEUS DOS VIAJANTES E MENSAGEIROS', caption:'HERMES · ESTRADA E VENTO', title:'Toda fronteira<br>guarda uma <em>passagem.</em>', description:'Mensageiro dos deuses e patrono dos viajantes, Hermes conhece atalhos entre mundos, cidades e estados de espírito.', quoteSource:'AS ESTRADAS DA ÁRCADIA', quote:'“Às vezes, o caminho aparece quando alguém se põe a andar.”', kicker:'CADERNO DE HERMES', image:'assets/hermes.png',
    stories:[['01 · INVENÇÃO','A lira feita de casco','Uma tartaruga, algumas cordas e o primeiro instrumento de Hermes.','5 MIN','Ϻ','Ainda bebê, Hermes roubou o rebanho de Apollo e apagou os rastros. Para apaziguar o irmão, apresentou uma lira feita com o casco de uma tartaruga. Apollo aceitou o instrumento, e a disputa terminou em troca.'],['02 · MISSÃO','Argos e os cem olhos','Hermes atravessa a guarda de um gigante com conversa e música.','5 MIN','☼','Hera confiou Io ao gigante Argos Panoptes. Hermes foi enviado para libertá-la e tocou flauta até adormecer o guardião. O mensageiro mostra a eloquência como ferramenta de ação.'],['03 · TRAVESSIA','O guia das almas','Hermes acompanha os mortos na passagem para outro mundo.','4 MIN','∿','Como Hermes Psicopompo, o deus guiava as almas até a entrada do submundo. O mesmo mensageiro que cruzava fronteiras para os vivos acompanhava os mortos no caminho final.']]
  },
  dionysus: {
    index:'12', name:'Dionísio', symbol:'Δ', specialty:'Vinho & teatro', domain:'DEUS DO VINHO E DO TEATRO', caption:'DIONÍSIO · VINHO E MÁSCARA', title:'A máscara<br>revela outra <em>face.</em>', description:'Deus do teatro, do vinho e do êxtase, Dionísio suspende as regras para mostrar o que a rotina esconde.', quoteSource:'AS ENCOSTAS DE CÍTERON', quote:'“Às vezes, é preciso sair de si para enxergar.”', kicker:'CADERNO DE DIONÍSIO', image:'assets/dionysus.png',
    stories:[['01 · TEATRO','O rei que não acreditou','Penteu tenta negar o culto de Dionísio e perde o controle da própria cidade.','7 MIN','Δ','Dionísio voltou a Tebas, mas o rei Penteu recusou-se a reconhecer o deus. A tragédia de Eurípides acompanha o confronto e mostra como a repressão do desconhecido pode se voltar contra quem acredita controlá-lo.'],['02 · TRAVESSIA','Os piratas e os golfinhos','Marinheiros tentam raptar um passageiro que o mar não pode conter.','5 MIN','∿','Piratas confundiram Dionísio com um jovem príncipe e o capturaram. O deus fez crescer vinhas pelo navio e transformou os remos em serpentes; os marinheiros saltaram ao mar e viraram golfinhos.'],['03 · PALCO','A origem das máscaras','Uma celebração coletiva dá forma ao teatro e aos seus personagens.','5 MIN','◇','As festas de Dionísio reuniam canto, dança e procissões. Em Atenas, festivais urbanos tornaram-se espaço para tragédia e comédia; a máscara permitia ao ator mudar de papel diante da comunidade.']]
  }
};

const olympianOrder = ['zeus','hera','poseidon','demeter','athena','apollo','artemis','ares','aphrodite','hephaestus','hermes','dionysus'];
const renderGodTab = (key) => { const god = gods[key]; return `<button class="god-tab" role="tab" aria-selected="false" data-god="${key}"><span class="god-symbol">${god.symbol}</span><span class="god-text"><strong>${god.name}</strong><small>${god.specialty}</small></span><span class="god-count">${god.index}</span></button>`; };
document.querySelector('#godSelector').innerHTML = olympianOrder.map(renderGodTab).join('');
document.querySelector('#extraGodSelector').innerHTML = renderGodTab('hades');
const body = document.body;
const tabs = [...document.querySelectorAll('.god-tab')];
const setGod = (key) => {
  const god = gods[key] || gods.athena;
  body.dataset.god = key;
  document.querySelector('#heroDomain').textContent = god.domain;
  document.querySelector('#heroCaption').textContent = god.caption;
  document.querySelector('#heroIndex').textContent = god.index;
  document.querySelector('#heroTotal').textContent = `${god.index} — 13`;
  document.querySelector('#heroTitle').innerHTML = god.title;
  document.querySelector('#heroDescription').textContent = god.description;
  document.querySelector('#heroImage').src = god.image;
  document.querySelector('#heroImage').alt = `Representação em escultura grega de ${god.name}`;
  document.querySelector('#storyKicker').textContent = god.kicker;
  document.querySelector('#quoteSource').textContent = god.quoteSource;
  document.querySelector('#quoteText').textContent = god.quote;
  document.querySelector('meta[name="theme-color"]').content = getComputedStyle(body).getPropertyValue('--paper').trim();
  tabs.forEach(tab => { const active = tab.dataset.god === key; tab.classList.toggle('is-active',active); tab.setAttribute('aria-selected',String(active)); });
  document.querySelector('#storyGrid').innerHTML = god.stories.map(([meta,title,description,time,mark,body]) => `<article class="story-card" data-mark="${mark}" data-title="${title}" data-body="${body}" tabindex="0" role="button" aria-label="Ler: ${title}"><div class="story-meta"><span>${meta.split(' · ')[0]}</span><span class="meta-dot"></span><span>${meta.split(' · ')[1]}</span></div><h3>${title}</h3><p>${description}</p><div class="story-footer"><span>${time}</span><span class="story-read" aria-hidden="true">↗</span></div></article>`).join('');
};

tabs.forEach(tab => tab.addEventListener('click', () => setGod(tab.dataset.god)));
document.querySelector('#randomStory').addEventListener('click', () => {
  const keys = Object.keys(gods);
  const key = keys[Math.floor(Math.random() * keys.length)];
  setGod(key);
  document.querySelector('#mitos').scrollIntoView({behavior:'smooth'});
});
document.querySelector('.mobile-menu').addEventListener('click', (event) => {
  const nav = document.querySelector('.main-nav');
  const open = nav.classList.toggle('mobile-open');
  event.currentTarget.setAttribute('aria-expanded',String(open));
});
const storyDialog = document.querySelector('#storyDialog');
const openStory = (card) => { document.querySelector('#dialogEyebrow').textContent = gods[body.dataset.god].kicker; document.querySelector('#dialogTitle').textContent = card.dataset.title; document.querySelector('#dialogBody').textContent = card.dataset.body; storyDialog.showModal(); };
document.querySelector('#storyGrid').addEventListener('click', event => { const card = event.target.closest('.story-card'); if (card) openStory(card); });
document.querySelector('#storyGrid').addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { const card = event.target.closest('.story-card'); if (card) { event.preventDefault(); openStory(card); } } });
document.querySelector('#dialogClose').addEventListener('click', () => storyDialog.close());
storyDialog.addEventListener('click', event => { if (event.target === storyDialog) storyDialog.close(); });
setGod('athena');
